CREATE DATABASE `todoapp`;

DROP TABLE IF EXISTS `todos`;
CREATE TABLE `todos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `user_id` SMALLINT UNSIGNED NOT NULL,
  `task` VARCHAR(255) NOT NULL,
  `completed` TINYINT(1),
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);



